version: '3.8'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    environment:
      RABBITMQ_ERLANG_COOKIE: 'a_secret_cookie'
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'
      RABBITMQ_CONFIG_FILE: '/etc/rabbitmq/rabbitmq'
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: '-rabbitmq_management load_definitions "/etc/rabbitmq/definitions.json"'
    depends_on:
      - timescaledb
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/timescaledb/data
      - ./timescaledb/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  amqp_consumer:
    build:
      context: ./amqp_consumer
    depends_on:
      - rabbitmq
      - timescaledb
    environment:
      POSTGRES_HOST: timescaledb
      RABBITMQ_HOST: rabbitmq
    env_file:
      - amqp_consumer.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:your_amqp_consumer_port/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - timescaledb
      - rabbitmq
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  timescaledb_data:
  grafana_data:
