apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\blake\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  type: NodePort
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "15672"
      port: 15672
      targetPort: 15672
  selector:
    io.kompose.service: rabbitmq
