apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: rabbitmq
spec:
  clusterIP: None
  ports:
    - port: 4369
      name: epmd
    - port: 25672
      name: inter-node
  selector:
    app: rabbitmq
